### ISSUE TITLE
Siri emulation in real time map

### ISSUE THREAD

**Issue by jbtfk** [TromsFylkestrafikk/laravel-siri#40]
## Problem

laravel-siri provides an interface to upload siri xml files to emulate situation-data. Building this from the real time map is not working. Most probably due to difference in Vue versions (2.x vs 3.x) and different build system (Webpack for laravel-siri, Vite for real time map)

##  Definition of done
- [x] laravel-siri emulation is buildable from laravel-siri
- [x] Document process

**Comment by jbtfk** [comment]
As far as I understand this, siri-emulation would be a second bundle in to build in a project like the real time map (at least the way it was built with webpack and mix). And I don't think vite supports multiple input/bundles out of the box (https://deployhook.com/blog/vite-multiple-configs/)

**Comment by jbtfk** [comment]
Implemented a hack to enable building emulator from laravel-siri and making local subscriptions in rtm

- checkout linked branch
- run `npx mix`
- copy public/siri/js folder to rtm public/siri/js
- remember to add test subscription in rtm

**Comment by tfk-kaare** [comment]
I think that is enough. A separate issue is to omit the uuid check on incoming xml during development.

What I mean is: By documenting this process in README.md, it solves our basic needs.

We could investigate the use of laravel's vendor:publish stuff to export things to the installed app.

Otherwise, the webpack fix and documenting it is enough for this :-)
